from pathlib import Path

repo = Path('.')
header_path = repo / 'src/ui_manager.h'
ui_path = repo / 'src/ui_manager.cpp'
main_path = repo / 'src/main.cpp'

header = header_path.read_text(encoding='utf-8')
ui = ui_path.read_text(encoding='utf-8')
main = main_path.read_text(encoding='utf-8')

old = '''    open_settings,\n    open_save_load,\n    save_game,\n    load_game,\n    back_to_pause,\n    close_modal,\n'''
new = '''    open_settings,\n    open_main_menu,\n    open_save_load,\n    save_game,\n    load_game,\n    back_to_pause,\n    back_from_save_load,\n    open_quit_confirm,\n    cancel_quit,\n    quit_game,\n    close_modal,\n'''
if old not in header:
    raise SystemExit('UiAction insertion point not found')
header = header.replace(old, new, 1)

old = '''    reports,\n    settings,\n    save_load,\n};\n'''
new = '''    reports,\n    settings,\n    main_menu,\n    save_load,\n    quit_confirm,\n};\n'''
if old not in header:
    raise SystemExit('UiOverlay insertion point not found')
header = header.replace(old, new, 1)

old = '''        pause_button(0, "CONTINUAR", UiAction::resume_game, true);\n        pause_button(1, "SALVAR JOGO", UiAction::open_save_load, true);\n        pause_button(2, "CARREGAR JOGO", UiAction::open_save_load, true);\n        pause_button(3, "CONFIGURACOES", UiAction::none, false);\n        pause_button(4, "MENU PRINCIPAL", UiAction::none, false);\n        pause_button(5, "SAIR DO JOGO", UiAction::none, false);\n    } else if (model.overlay == UiOverlay::save_load) {\n'''
new = '''        pause_button(0, "CONTINUAR", UiAction::resume_game, true);\n        pause_button(1, "SALVAR JOGO", UiAction::open_save_load, true);\n        pause_button(2, "CARREGAR JOGO", UiAction::open_save_load, true);\n        pause_button(3, "CONFIGURACOES", UiAction::open_settings, true);\n        pause_button(4, "MENU PRINCIPAL", UiAction::open_main_menu, true);\n        pause_button(5, "SAIR DO JOGO", UiAction::open_quit_confirm, true);\n    } else if (model.overlay == UiOverlay::main_menu) {\n        const float panel_width = std::min(560.0F, std::max(340.0F, width - 48.0F));\n        const float panel_height = std::min(520.0F, std::max(430.0F, height - 64.0F));\n        const UiRect panel = {(width - panel_width) * 0.5F, (height - panel_height) * 0.5F, panel_width, panel_height};\n        overlay_bounds_ = panel;\n        const float padding = std::clamp(panel.width * 0.065F, 22.0F, 36.0F);\n        const float button_width = panel.width - padding * 2.0F;\n        const float button_top = panel.y + 190.0F;\n        const float button_gap = 10.0F;\n        const float button_height = 48.0F;\n        add_button({panel.x + padding, button_top, button_width, button_height}, "CONTINUAR CIDADE", UiAction::resume_game);\n        add_button({panel.x + padding, button_top + (button_height + button_gap), button_width, button_height}, "SALVAR / CARREGAR", UiAction::open_save_load);\n        add_button({panel.x + padding, button_top + (button_height + button_gap) * 2.0F, button_width, button_height}, "CONFIGURACOES", UiAction::open_settings);\n        add_button({panel.x + padding, button_top + (button_height + button_gap) * 3.0F, button_width, button_height}, "SAIR DO JOGO", UiAction::open_quit_confirm);\n    } else if (model.overlay == UiOverlay::quit_confirm) {\n        const float panel_width = std::min(500.0F, std::max(340.0F, width - 48.0F));\n        const float panel_height = std::min(300.0F, std::max(260.0F, height - 96.0F));\n        const UiRect panel = {(width - panel_width) * 0.5F, (height - panel_height) * 0.5F, panel_width, panel_height};\n        overlay_bounds_ = panel;\n        const float padding = std::clamp(panel.width * 0.07F, 24.0F, 36.0F);\n        const float gap = 12.0F;\n        const float button_width = (panel.width - padding * 2.0F - gap) * 0.5F;\n        const float button_y = panel.y + panel.height - 70.0F;\n        add_button({panel.x + padding, button_y, button_width, 44.0F}, "CANCELAR", UiAction::cancel_quit);\n        add_button({panel.x + padding + button_width + gap, button_y, button_width, 44.0F}, "SAIR", UiAction::quit_game);\n    } else if (model.overlay == UiOverlay::save_load) {\n'''
if old not in ui:
    raise SystemExit('pause layout block not found')
ui = ui.replace(old, new, 1)

old = '''        add_button({panel.x + horizontal_padding, button_y, button_width, 42.0F}, "SALVAR AGORA", UiAction::save_game);\n        add_button({panel.x + horizontal_padding + button_width + button_gap, button_y, button_width, 42.0F}, "CARREGAR", UiAction::load_game, model.save_available);\n        add_button({panel.x + horizontal_padding + (button_width + button_gap) * 2.0F, button_y, button_width, 42.0F}, "VOLTAR", UiAction::back_to_pause);\n'''
new = '''        add_button({panel.x + horizontal_padding, button_y, button_width, 42.0F}, "SALVAR AGORA", UiAction::save_game);\n        add_button({panel.x + horizontal_padding + button_width + button_gap, button_y, button_width, 42.0F}, "CARREGAR", UiAction::load_game, model.save_available);\n        add_button({panel.x + horizontal_padding + (button_width + button_gap) * 2.0F, button_y, button_width, 42.0F}, "VOLTAR", UiAction::back_from_save_load);\n'''
if old not in ui:
    raise SystemExit('save load back button not found')
ui = ui.replace(old, new, 1)

anchor = '''        if (model_.overlay == UiOverlay::save_load) {\n'''
insert = '''        if (model_.overlay == UiOverlay::main_menu) {\n            draw_pause_panel(renderer, panel);\n            draw_text_centered(renderer, panel, panel.y + 38.0F, "CITY HORIZON", 238, 246, 249);\n            draw_text_centered(renderer, panel, panel.y + 68.0F, "MENU PRINCIPAL", 158, 186, 199);\n\n            const float info_x = panel.x + std::clamp(panel.width * 0.08F, 28.0F, 44.0F);\n            const float info_width = panel.width - (info_x - panel.x) * 2.0F;\n            const SDL_FRect info = {info_x, panel.y + 98.0F, info_width, 68.0F};\n            SDL_SetRenderDrawColor(renderer, 20, 44, 59, 252);\n            SDL_RenderFillRect(renderer, &info);\n            SDL_SetRenderDrawColor(renderer, 64, 103, 123, SDL_ALPHA_OPAQUE);\n            SDL_RenderRect(renderer, &info);\n            draw_text(renderer, info.x + 14.0F, info.y + 12.0F, "CIDADE ATUAL", 158, 186, 199);\n            draw_text_fit(renderer, info.x + 14.0F, info.y + 33.0F, info.w - 28.0F,\n                          model_.day_month + " | " + model_.year + " | " + model_.funds, 219, 232, 238);\n            draw_text_fit(renderer, info.x + 14.0F, info.y + 50.0F, info.w - 28.0F,\n                          "POPULACAO " + model_.population + " / " + model_.residential_capacity, 158, 186, 199);\n\n            for (const UiButton& button : buttons_) {\n                if (button.action == UiAction::resume_game || button.action == UiAction::open_save_load ||\n                    button.action == UiAction::open_settings || button.action == UiAction::open_quit_confirm) {\n                    draw_pause_button(renderer, button);\n                }\n            }\n            draw_text_centered(renderer, panel, panel.y + panel.height - 20.0F, "ESC  -  VOLTAR AO PAUSE", 158, 186, 199);\n            return;\n        }\n\n        if (model_.overlay == UiOverlay::quit_confirm) {\n            draw_pause_panel(renderer, panel);\n            draw_text_centered(renderer, panel, panel.y + 42.0F, "SAIR DO JOGO?", 238, 246, 249);\n            draw_text_centered(renderer, panel, panel.y + 82.0F, "ALTERACOES NAO SALVAS SERAO PERDIDAS", 255, 180, 160);\n            draw_text_centered(renderer, panel, panel.y + 108.0F, "SALVE A CIDADE ANTES DE ENCERRAR SE NECESSARIO", 158, 186, 199);\n            for (const UiButton& button : buttons_) {\n                if (button.action == UiAction::cancel_quit || button.action == UiAction::quit_game) {\n                    draw_pause_button(renderer, button);\n                }\n            }\n            draw_text_centered(renderer, panel, panel.y + panel.height - 20.0F, "ESC  -  CANCELAR", 158, 186, 199);\n            return;\n        }\n\n'''
if anchor not in ui:
    raise SystemExit('save load render anchor not found')
ui = ui.replace(anchor, insert + anchor, 1)

old = '''    UiOverlay active_overlay = UiOverlay::none;\n    bool debug_visible = false;\n'''
new = '''    UiOverlay active_overlay = UiOverlay::none;\n    UiOverlay settings_return_overlay = UiOverlay::none;\n    UiOverlay save_load_return_overlay = UiOverlay::pause;\n    UiOverlay quit_return_overlay = UiOverlay::pause;\n    bool debug_visible = false;\n'''
if old not in main:
    raise SystemExit('overlay state insertion point not found')
main = main.replace(old, new, 1)

old = '''            case UiAction::open_settings:\n                active_overlay = UiOverlay::settings;\n                status = "SETTINGS OPEN";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::open_save_load:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = UiOverlay::save_load;\n                status = std::filesystem::exists(save_path) ? "SAVE SLOT READY" : "SAVE SLOT EMPTY";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n'''
new = '''            case UiAction::open_settings:\n                settings_return_overlay = active_overlay == UiOverlay::pause || active_overlay == UiOverlay::main_menu\n                    ? active_overlay : UiOverlay::none;\n                active_overlay = UiOverlay::settings;\n                status = "SETTINGS OPEN";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::open_main_menu:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = UiOverlay::main_menu;\n                status = "MAIN MENU OPEN";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::open_save_load:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                save_load_return_overlay = active_overlay == UiOverlay::main_menu ? UiOverlay::main_menu : UiOverlay::pause;\n                active_overlay = UiOverlay::save_load;\n                status = std::filesystem::exists(save_path) ? "SAVE SLOT READY" : "SAVE SLOT EMPTY";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n'''
if old not in main:
    raise SystemExit('open settings/save block not found')
main = main.replace(old, new, 1)

old = '''            case UiAction::back_to_pause:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = UiOverlay::pause;\n                status = "GAME PAUSED";\n                (void)audio.play(SoundEvent::ui_back);\n                break;\n            case UiAction::close_modal:\n            case UiAction::settings_cancel:\n                active_overlay = UiOverlay::none;\n                status = "PANEL CLOSED";\n                (void)audio.play(SoundEvent::ui_close_panel);\n                break;\n'''
new = '''            case UiAction::back_to_pause:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = UiOverlay::pause;\n                status = "GAME PAUSED";\n                (void)audio.play(SoundEvent::ui_back);\n                break;\n            case UiAction::back_from_save_load:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = save_load_return_overlay;\n                status = active_overlay == UiOverlay::main_menu ? "MAIN MENU OPEN" : "GAME PAUSED";\n                (void)audio.play(SoundEvent::ui_back);\n                break;\n            case UiAction::open_quit_confirm:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                quit_return_overlay = active_overlay == UiOverlay::main_menu ? UiOverlay::main_menu : UiOverlay::pause;\n                active_overlay = UiOverlay::quit_confirm;\n                status = "CONFIRM EXIT";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::cancel_quit:\n                active_overlay = quit_return_overlay;\n                status = active_overlay == UiOverlay::main_menu ? "MAIN MENU OPEN" : "GAME PAUSED";\n                (void)audio.play(SoundEvent::ui_back);\n                break;\n            case UiAction::quit_game:\n                status = "EXITING CITY HORIZON";\n                (void)audio.play(SoundEvent::ui_confirm);\n                running = false;\n                break;\n            case UiAction::close_modal:\n                active_overlay = UiOverlay::none;\n                status = "PANEL CLOSED";\n                (void)audio.play(SoundEvent::ui_close_panel);\n                break;\n            case UiAction::settings_cancel:\n                active_overlay = settings_return_overlay;\n                status = active_overlay == UiOverlay::pause ? "GAME PAUSED" :\n                    (active_overlay == UiOverlay::main_menu ? "MAIN MENU OPEN" : "PANEL CLOSED");\n                (void)audio.play(SoundEvent::ui_close_panel);\n                break;\n'''
if old not in main:
    raise SystemExit('back/settings cancel block not found')
main = main.replace(old, new, 1)

old = '''                audio.set_volume_settings(volumes);\n                active_overlay = UiOverlay::none;\n                status = "SETTINGS APPLIED";\n                (void)audio.play(SoundEvent::ui_confirm);\n'''
new = '''                audio.set_volume_settings(volumes);\n                active_overlay = settings_return_overlay;\n                status = active_overlay == UiOverlay::pause ? "SETTINGS APPLIED - GAME PAUSED" :\n                    (active_overlay == UiOverlay::main_menu ? "SETTINGS APPLIED - MAIN MENU" : "SETTINGS APPLIED");\n                (void)audio.play(SoundEvent::ui_confirm);\n'''
if old not in main:
    raise SystemExit('settings apply return block not found')
main = main.replace(old, new, 1)

old = '''                        if (active_overlay == UiOverlay::pause) {\n                            apply_ui_action({UiAction::resume_game, {}});\n                        } else if (active_overlay == UiOverlay::save_load) {\n                            apply_ui_action({UiAction::back_to_pause, {}});\n                        } else {\n                            active_overlay = UiOverlay::none;\n                            status = "PANEL CLOSED";\n                            (void)audio.play(SoundEvent::ui_close_panel);\n                        }\n'''
new = '''                        if (active_overlay == UiOverlay::pause) {\n                            apply_ui_action({UiAction::resume_game, {}});\n                        } else if (active_overlay == UiOverlay::save_load) {\n                            apply_ui_action({UiAction::back_from_save_load, {}});\n                        } else if (active_overlay == UiOverlay::settings) {\n                            apply_ui_action({UiAction::settings_cancel, {}});\n                        } else if (active_overlay == UiOverlay::main_menu) {\n                            apply_ui_action({UiAction::back_to_pause, {}});\n                        } else if (active_overlay == UiOverlay::quit_confirm) {\n                            apply_ui_action({UiAction::cancel_quit, {}});\n                        } else {\n                            active_overlay = UiOverlay::none;\n                            status = "PANEL CLOSED";\n                            (void)audio.play(SoundEvent::ui_close_panel);\n                        }\n'''
if old not in main:
    raise SystemExit('overlay escape block not found')
main = main.replace(old, new, 1)

header_path.write_text(header, encoding='utf-8')
ui_path.write_text(ui, encoding='utf-8')
main_path.write_text(main, encoding='utf-8')
