from pathlib import Path


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'{label}: expected block not found in {path}')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')

header = Path('src/ui_manager.h')
replace_once(header,
'''    open_settings,\n    open_main_menu,\n    open_save_load,\n''',
'''    open_settings,\n    open_main_menu,\n    start_new_city,\n    continue_saved_city,\n    open_save_load,\n''',
'ui actions')
replace_once(header,
'''    bool save_available = false;\n    UiTool active_tool = UiTool::none;\n''',
'''    bool save_available = false;\n    bool startup_main_menu = false;\n    UiTool active_tool = UiTool::none;\n''',
'ui model startup flag')

ui = Path('src/ui_manager.cpp')
replace_once(ui,
'''    } else if (model.overlay == UiOverlay::main_menu) {\n        const float panel_width = std::min(560.0F, std::max(340.0F, width - 48.0F));\n        const float panel_height = std::min(520.0F, std::max(430.0F, height - 64.0F));\n        const UiRect panel = {(width - panel_width) * 0.5F, (height - panel_height) * 0.5F, panel_width, panel_height};\n        overlay_bounds_ = panel;\n        const float padding = std::clamp(panel.width * 0.065F, 22.0F, 36.0F);\n        const float button_width = panel.width - padding * 2.0F;\n        const float button_top = panel.y + 190.0F;\n        const float button_gap = 10.0F;\n        const float button_height = 48.0F;\n        add_button({panel.x + padding, button_top, button_width, button_height}, "CONTINUAR CIDADE", UiAction::resume_game);\n        add_button({panel.x + padding, button_top + (button_height + button_gap), button_width, button_height}, "SALVAR / CARREGAR", UiAction::open_save_load);\n        add_button({panel.x + padding, button_top + (button_height + button_gap) * 2.0F, button_width, button_height}, "CONFIGURACOES", UiAction::open_settings);\n        add_button({panel.x + padding, button_top + (button_height + button_gap) * 3.0F, button_width, button_height}, "SAIR DO JOGO", UiAction::open_quit_confirm);\n''',
'''    } else if (model.overlay == UiOverlay::main_menu) {\n        const float panel_width = std::min(560.0F, std::max(340.0F, width - 48.0F));\n        const float panel_height = std::min(520.0F, std::max(430.0F, height - 64.0F));\n        const UiRect panel = {(width - panel_width) * 0.5F, (height - panel_height) * 0.5F, panel_width, panel_height};\n        overlay_bounds_ = panel;\n        const float padding = std::clamp(panel.width * 0.065F, 22.0F, 36.0F);\n        const float button_width = panel.width - padding * 2.0F;\n        const float button_top = panel.y + 190.0F;\n        const float button_gap = 10.0F;\n        const float button_height = 48.0F;\n        if (model.startup_main_menu) {\n            add_button({panel.x + padding, button_top, button_width, button_height}, "NOVA CIDADE", UiAction::start_new_city);\n            add_button({panel.x + padding, button_top + (button_height + button_gap), button_width, button_height},\n                       "CONTINUAR CIDADE", UiAction::continue_saved_city, model.save_available);\n        } else {\n            add_button({panel.x + padding, button_top, button_width, button_height}, "CONTINUAR CIDADE", UiAction::resume_game);\n            add_button({panel.x + padding, button_top + (button_height + button_gap), button_width, button_height},\n                       "SALVAR / CARREGAR", UiAction::open_save_load);\n        }\n        add_button({panel.x + padding, button_top + (button_height + button_gap) * 2.0F, button_width, button_height}, "CONFIGURACOES", UiAction::open_settings);\n        add_button({panel.x + padding, button_top + (button_height + button_gap) * 3.0F, button_width, button_height}, "SAIR DO JOGO", UiAction::open_quit_confirm);\n''',
'main menu layout')
replace_once(ui,
'''            const float info_x = panel.x + std::clamp(panel.width * 0.08F, 28.0F, 44.0F);\n            const float info_width = panel.width - (info_x - panel.x) * 2.0F;\n            const SDL_FRect info = {info_x, panel.y + 98.0F, info_width, 68.0F};\n            SDL_SetRenderDrawColor(renderer, 20, 44, 59, 252);\n            SDL_RenderFillRect(renderer, &info);\n            SDL_SetRenderDrawColor(renderer, 64, 103, 123, SDL_ALPHA_OPAQUE);\n            SDL_RenderRect(renderer, &info);\n            draw_text(renderer, info.x + 14.0F, info.y + 12.0F, "CIDADE ATUAL", 158, 186, 199);\n            draw_text_fit(renderer, info.x + 14.0F, info.y + 33.0F, info.w - 28.0F,\n                          model_.day_month + " | " + model_.year + " | " + model_.funds, 219, 232, 238);\n            draw_text_fit(renderer, info.x + 14.0F, info.y + 50.0F, info.w - 28.0F,\n                          "POPULACAO " + model_.population + " / " + model_.residential_capacity, 158, 186, 199);\n\n            for (const UiButton& button : buttons_) {\n                if (button.action == UiAction::resume_game || button.action == UiAction::open_save_load ||\n                    button.action == UiAction::open_settings || button.action == UiAction::open_quit_confirm) {\n                    draw_pause_button(renderer, button);\n                }\n            }\n            draw_text_centered(renderer, panel, panel.y + panel.height - 20.0F, "ESC  -  VOLTAR AO PAUSE", 158, 186, 199);\n''',
'''            const float info_x = panel.x + std::clamp(panel.width * 0.08F, 28.0F, 44.0F);\n            const float info_width = panel.width - (info_x - panel.x) * 2.0F;\n            const SDL_FRect info = {info_x, panel.y + 98.0F, info_width, 68.0F};\n            SDL_SetRenderDrawColor(renderer, 20, 44, 59, 252);\n            SDL_RenderFillRect(renderer, &info);\n            SDL_SetRenderDrawColor(renderer, 64, 103, 123, SDL_ALPHA_OPAQUE);\n            SDL_RenderRect(renderer, &info);\n            if (model_.startup_main_menu) {\n                draw_text(renderer, info.x + 14.0F, info.y + 12.0F, "BEM-VINDO", 158, 186, 199);\n                draw_text_fit(renderer, info.x + 14.0F, info.y + 33.0F, info.w - 28.0F,\n                              "ESCOLHA COMO COMECAR SUA CIDADE", 219, 232, 238);\n                draw_text_fit(renderer, info.x + 14.0F, info.y + 50.0F, info.w - 28.0F,\n                              model_.save_available ? "SAVE EXISTENTE DETECTADO" : "NENHUM SAVE EXISTENTE",\n                              158, 186, 199);\n            } else {\n                draw_text(renderer, info.x + 14.0F, info.y + 12.0F, "CIDADE ATUAL", 158, 186, 199);\n                draw_text_fit(renderer, info.x + 14.0F, info.y + 33.0F, info.w - 28.0F,\n                              model_.day_month + " | " + model_.year + " | " + model_.funds, 219, 232, 238);\n                draw_text_fit(renderer, info.x + 14.0F, info.y + 50.0F, info.w - 28.0F,\n                              "POPULACAO " + model_.population + " / " + model_.residential_capacity, 158, 186, 199);\n            }\n\n            for (const UiButton& button : buttons_) {\n                if (button.action == UiAction::resume_game || button.action == UiAction::start_new_city ||\n                    button.action == UiAction::continue_saved_city || button.action == UiAction::open_save_load ||\n                    button.action == UiAction::open_settings || button.action == UiAction::open_quit_confirm) {\n                    draw_pause_button(renderer, button);\n                }\n            }\n            draw_text_centered(renderer, panel, panel.y + panel.height - 20.0F,\n                               model_.startup_main_menu ? "ESC  -  SAIR" : "ESC  -  VOLTAR AO PAUSE", 158, 186, 199);\n''',
'main menu rendering')

main = Path('src/main.cpp')
replace_once(main,
'''    std::string status = "CLICK A BUILDING TO SELECT IT";\n    UiOverlay active_overlay = UiOverlay::none;\n    UiOverlay settings_return_overlay = UiOverlay::none;\n''',
'''    std::string status = "MAIN MENU";\n    UiOverlay active_overlay = UiOverlay::main_menu;\n    bool startup_main_menu = true;\n    simulation_clock.set_speed(SimulationSpeed::paused);\n    UiOverlay settings_return_overlay = UiOverlay::none;\n''',
'startup overlay state')
replace_once(main,
'''            case UiAction::open_main_menu:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = UiOverlay::main_menu;\n                status = "MAIN MENU OPEN";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::open_save_load:\n''',
'''            case UiAction::open_main_menu:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                startup_main_menu = false;\n                active_overlay = UiOverlay::main_menu;\n                status = "MAIN MENU OPEN";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::start_new_city:\n                clear_map_modes();\n                build_panel_open = false;\n                selected_instance_id.reset();\n                startup_main_menu = false;\n                active_overlay = UiOverlay::none;\n                simulation_clock.set_speed(SimulationSpeed::speed1);\n                last_simulation_ticks = SDL_GetTicks();\n                simulation_scheduler.reset();\n                status = "NEW CITY STARTED";\n                (void)audio.play(SoundEvent::ui_confirm);\n                break;\n            case UiAction::continue_saved_city:\n                if (!std::filesystem::exists(save_path)) {\n                    status = "NO SAVE AVAILABLE";\n                    (void)audio.play(SoundEvent::ui_error);\n                    break;\n                }\n                if (load_current_city(false)) {\n                    startup_main_menu = false;\n                    active_overlay = UiOverlay::none;\n                    simulation_clock.set_speed(SimulationSpeed::speed1);\n                    last_simulation_ticks = SDL_GetTicks();\n                    simulation_scheduler.reset();\n                    status = "CITY CONTINUED";\n                }\n                break;\n            case UiAction::open_save_load:\n''',
'start and continue actions')
replace_once(main,
'''        model.save_available = std::filesystem::exists(save_path);\n        model.build_panel_open = build_panel_open;\n''',
'''        model.save_available = std::filesystem::exists(save_path);\n        model.startup_main_menu = startup_main_menu;\n        model.build_panel_open = build_panel_open;\n''',
'ui startup model flag')
replace_once(main,
'''                        } else if (active_overlay == UiOverlay::main_menu) {\n                            apply_ui_action({UiAction::back_to_pause, {}});\n                        } else if (active_overlay == UiOverlay::quit_confirm) {\n''',
'''                        } else if (active_overlay == UiOverlay::main_menu) {\n                            apply_ui_action({startup_main_menu ? UiAction::open_quit_confirm : UiAction::back_to_pause, {}});\n                        } else if (active_overlay == UiOverlay::quit_confirm) {\n''',
'startup escape behavior')
