from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"Pattern changed: {label}")
    return text.replace(old, new, 1)


# ui_manager.h
path = Path("src/ui_manager.h")
text = path.read_text(encoding="utf-8")
text = replace_once(text, """    open_reports,\n    open_settings,\n    close_modal,\n    settings_reset,""", """    open_reports,\n    open_settings,\n    open_save_load,\n    save_game,\n    load_game,\n    back_to_pause,\n    close_modal,\n    settings_reset,""", "UI actions")
text = replace_once(text, """    reports,\n    settings,\n};""", """    reports,\n    settings,\n    save_load,\n};""", "save load overlay")
text = replace_once(text, """    int effects_volume_percent = 100;\n    UiTool active_tool = UiTool::none;""", """    int effects_volume_percent = 100;\n    bool save_available = false;\n    UiTool active_tool = UiTool::none;""", "save availability model")
path.write_text(text, encoding="utf-8")


# ui_manager.cpp
path = Path("src/ui_manager.cpp")
text = path.read_text(encoding="utf-8")
text = replace_once(text, """        case UiOverlay::settings:\n        case UiOverlay::pause:\n        case UiOverlay::none: break;""", """        case UiOverlay::settings:\n        case UiOverlay::save_load:\n        case UiOverlay::pause:\n        case UiOverlay::none: break;""", "overlay path save load")
text = replace_once(text, """        pause_button(0, \"CONTINUAR\", UiAction::resume_game, true);\n        pause_button(1, \"SALVAR JOGO\", UiAction::none, false);\n        pause_button(2, \"CARREGAR JOGO\", UiAction::none, false);\n        pause_button(3, \"CONFIGURACOES\", UiAction::none, false);""", """        pause_button(0, \"CONTINUAR\", UiAction::resume_game, true);\n        pause_button(1, \"SALVAR JOGO\", UiAction::open_save_load, true);\n        pause_button(2, \"CARREGAR JOGO\", UiAction::open_save_load, true);\n        pause_button(3, \"CONFIGURACOES\", UiAction::none, false);""", "enable pause save load")
text = replace_once(text, """    } else if (model.overlay == UiOverlay::settings) {\n        const float panel_width = std::min(620.0F, std::max(360.0F, width - 48.0F));""", """    } else if (model.overlay == UiOverlay::save_load) {\n        const float panel_width = std::min(620.0F, std::max(360.0F, width - 48.0F));\n        const float panel_height = std::min(440.0F, std::max(370.0F, height - 64.0F));\n        const UiRect panel = {(width - panel_width) * 0.5F, (height - panel_height) * 0.5F, panel_width, panel_height};\n        overlay_bounds_ = panel;\n        const float horizontal_padding = std::clamp(panel.width * 0.06F, 22.0F, 36.0F);\n        const float button_gap = 12.0F;\n        const float button_y = panel.y + panel.height - 70.0F;\n        const float available = panel.width - horizontal_padding * 2.0F - button_gap * 2.0F;\n        const float button_width = available / 3.0F;\n        add_button({panel.x + horizontal_padding, button_y, button_width, 42.0F}, \"SALVAR AGORA\", UiAction::save_game);\n        add_button({panel.x + horizontal_padding + button_width + button_gap, button_y, button_width, 42.0F}, \"CARREGAR\", UiAction::load_game, model.save_available);\n        add_button({panel.x + horizontal_padding + (button_width + button_gap) * 2.0F, button_y, button_width, 42.0F}, \"VOLTAR\", UiAction::back_to_pause);\n    } else if (model.overlay == UiOverlay::settings) {\n        const float panel_width = std::min(620.0F, std::max(360.0F, width - 48.0F));""", "save load layout")
text = replace_once(text, """        if (model_.overlay == UiOverlay::settings) {\n            draw_pause_panel(renderer, panel);""", """        if (model_.overlay == UiOverlay::save_load) {\n            draw_pause_panel(renderer, panel);\n            draw_text_centered(renderer, panel, panel.y + 36.0F, \"SALVAR / CARREGAR\", 238, 246, 249);\n            draw_text_centered(renderer, panel, panel.y + 66.0F, \"SLOT PRINCIPAL\", 158, 186, 199);\n\n            const float card_x = panel.x + std::clamp(panel.width * 0.08F, 28.0F, 48.0F);\n            const float card_width = panel.width - (card_x - panel.x) * 2.0F;\n            const UiRect slot_card = {card_x, panel.y + 102.0F, card_width, 156.0F};\n            const SDL_FRect slot_rect = {slot_card.x, slot_card.y, slot_card.width, slot_card.height};\n            SDL_SetRenderDrawColor(renderer, 20, 44, 59, 252);\n            SDL_RenderFillRect(renderer, &slot_rect);\n            SDL_SetRenderDrawColor(renderer, model_.save_available ? 91 : 64, model_.save_available ? 188 : 91,\n                                   model_.save_available ? 211 : 104, SDL_ALPHA_OPAQUE);\n            SDL_RenderRect(renderer, &slot_rect);\n\n            draw_text(renderer, slot_card.x + 18.0F, slot_card.y + 18.0F, \"CITY HORIZON - SLOT 1\", 238, 246, 249);\n            draw_text(renderer, slot_card.x + 18.0F, slot_card.y + 43.0F,\n                      model_.save_available ? \"SAVE DISPONIVEL\" : \"NENHUM SAVE ENCONTRADO\",\n                      model_.save_available ? 151 : 158, model_.save_available ? 229 : 151,\n                      model_.save_available ? 240 : 166);\n            draw_text(renderer, slot_card.x + 18.0F, slot_card.y + 78.0F, \"CIDADE ATUAL\", 158, 186, 199);\n            draw_text_fit(renderer, slot_card.x + 18.0F, slot_card.y + 100.0F, slot_card.width - 36.0F,\n                          model_.day_month + \" | \" + model_.year + \" | FUNDOS \" + model_.funds, 219, 232, 238);\n            draw_text_fit(renderer, slot_card.x + 18.0F, slot_card.y + 121.0F, slot_card.width - 36.0F,\n                          \"POPULACAO \" + model_.population + \" / \" + model_.residential_capacity, 158, 186, 199);\n\n            draw_text_fit(renderer, card_x, panel.y + 278.0F, card_width, model_.status, 158, 186, 199);\n            for (const UiButton& button : buttons_) {\n                if (button.action == UiAction::save_game || button.action == UiAction::load_game ||\n                    button.action == UiAction::back_to_pause) {\n                    draw_pause_button(renderer, button);\n                }\n            }\n            draw_text_centered(renderer, panel, panel.y + panel.height - 20.0F, \"ESC  -  VOLTAR AO PAUSE\", 158, 186, 199);\n            return;\n        }\n\n        if (model_.overlay == UiOverlay::settings) {\n            draw_pause_panel(renderer, panel);""", "save load render")
path.write_text(text, encoding="utf-8")


# main.cpp
path = Path("src/main.cpp")
text = path.read_text(encoding="utf-8")
text = replace_once(text, """    const auto apply_ui_action = [&](const UiActionEvent& action) {\n        switch (action.action) {""", """    const auto save_current_city = [&]() {\n        const SaveOperationResult result = save_manager.save(save_path, economy, simulation_clock, buildings, roads,\n                                                             sidewalks, farming, lands, population, &service_vehicles, &mission_manager);\n        status = result.success ? \"SAVE COMPLETE\" : \"SAVE FAILED: \" + result.message;\n        (void)audio.play(result.success ? SoundEvent::ui_confirm : SoundEvent::ui_error);\n        return result.success;\n    };\n    const auto load_current_city = [&](const bool keep_paused) {\n        const SaveOperationResult result = save_manager.load(save_path, catalog, economy, simulation_clock, buildings, roads,\n                                                             sidewalks, farming, lands, population, &service_vehicle_catalog,\n                                                             &service_vehicles, &mission_manager);\n        if (result.success) {\n            power.rebuild(buildings, catalog);\n            status = \"LOAD COMPLETE: \" + result.message;\n            if (mission_manager.check_and_auto_complete_clean_energy(economy, buildings, catalog, population, power)) {\n                status = \"MISSAO ENERGIA LIMPA CONCLUIDA! Hidreletrica Reativada!\";\n            }\n            selected_instance_id.reset();\n            clear_map_modes();\n            build_panel_open = false;\n            if (keep_paused) {\n                simulation_clock.set_speed(SimulationSpeed::paused);\n            } else if (simulation_clock.speed() != SimulationSpeed::paused) {\n                simulation_clock.set_speed(SimulationSpeed::speed1);\n            }\n            last_simulation_ticks = SDL_GetTicks();\n            simulation_scheduler.reset();\n            (void)audio.play(SoundEvent::ui_confirm);\n        } else {\n            status = \"LOAD FAILED: \" + result.message;\n            (void)audio.play(SoundEvent::ui_error);\n        }\n        return result.success;\n    };\n    const auto apply_ui_action = [&](const UiActionEvent& action) {\n        switch (action.action) {""", "save load helpers")
text = replace_once(text, """            case UiAction::open_settings:\n                active_overlay = UiOverlay::settings;\n                status = \"SETTINGS OPEN\";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::close_modal:""", """            case UiAction::open_settings:\n                active_overlay = UiOverlay::settings;\n                status = \"SETTINGS OPEN\";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::open_save_load:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = UiOverlay::save_load;\n                status = std::filesystem::exists(save_path) ? \"SAVE SLOT READY\" : \"SAVE SLOT EMPTY\";\n                (void)audio.play(SoundEvent::ui_open_panel);\n                break;\n            case UiAction::save_game:\n                (void)save_current_city();\n                break;\n            case UiAction::load_game:\n                (void)load_current_city(true);\n                break;\n            case UiAction::back_to_pause:\n                if (simulation_clock.speed() != SimulationSpeed::paused) simulation_clock.set_speed(SimulationSpeed::paused);\n                active_overlay = UiOverlay::pause;\n                status = \"GAME PAUSED\";\n                (void)audio.play(SoundEvent::ui_back);\n                break;\n            case UiAction::close_modal:""", "save load UI actions")
text = replace_once(text, """        model.effects_volume_percent = static_cast<int>(std::lround(audio.volume_settings().effects * 100.0F));\n        model.build_panel_open = build_panel_open;""", """        model.effects_volume_percent = static_cast<int>(std::lround(audio.volume_settings().effects * 100.0F));\n        model.save_available = std::filesystem::exists(save_path);\n        model.build_panel_open = build_panel_open;""", "save availability binding")
text = replace_once(text, """                    if (event.key.scancode == SDL_SCANCODE_ESCAPE) {\n                        if (active_overlay == UiOverlay::pause) {\n                            apply_ui_action({UiAction::resume_game, {}});\n                        } else {""", """                    if (event.key.scancode == SDL_SCANCODE_ESCAPE) {\n                        if (active_overlay == UiOverlay::pause) {\n                            apply_ui_action({UiAction::resume_game, {}});\n                        } else if (active_overlay == UiOverlay::save_load) {\n                            apply_ui_action({UiAction::back_to_pause, {}});\n                        } else {""", "save load escape behavior")
old_f5 = """                    case SDL_SCANCODE_F5: {\n                        const SaveOperationResult result = save_manager.save(save_path, economy, simulation_clock, buildings, roads, sidewalks, farming, lands, population, &service_vehicles, &mission_manager);\n                        status = result.success ? \"SAVE COMPLETE\" : \"SAVE FAILED: \" + result.message;\n                        (void)audio.play(result.success ? SoundEvent::ui_confirm : SoundEvent::ui_error);\n                        break;\n                    }"""
new_f5 = """                    case SDL_SCANCODE_F5:\n                        (void)save_current_city();\n                        break;"""
text = replace_once(text, old_f5, new_f5, "F5 shared save")
old_f9_start = text.find("                    case SDL_SCANCODE_F9: {")
old_f9_end = text.find("                    case SDL_SCANCODE_F10: {", old_f9_start)
if old_f9_start == -1 or old_f9_end == -1:
    raise SystemExit("Pattern changed: F9 load block")
text = text[:old_f9_start] + """                    case SDL_SCANCODE_F9:\n                        (void)load_current_city(false);\n                        break;\n""" + text[old_f9_end:]
path.write_text(text, encoding="utf-8")
